name: Build EXE

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: g++ -std=c++17 -O2 -static -static-libgcc -static-libstdc++ -pthread udin.cpp -o program.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: program.exe
